### ISSUE TITLE
What can use can do with RSS XML?

### ISSUE THREAD

**Issue by cbleek** [cbleek/JobArchive#3]
OK. A question comes up.

What can use can do with RSS XML?
Submit or Retrieve. Can you explain more about this part?

**Comment by cbleek** [comment]
@SJhumili 

The API should make it possible to create a public DATASET from job advertisements. With the DATASET we want to work in [JobClassification](https://github.com/cbleek/JobClassification).

Job advertisements should be transmitted in the form of a direct link or through a link to an RSS feed. 

We want the transmission of a link to be possible only as an authorized user.

A background process will go through and process the transmitted links. Some links will be discarded. Some links are accepted.

Maybe we should define a simple action POST "addLink".

**Comment by SJhumili** [comment]
I've checked JobClassification.
job{
"linkApply": 
"title": 
"logoRef": 
"link": 
"company": 
"id": 
"language": 
"location": 
"templateValues": {
	"tasks": 
	"requirements": 
	"description": 
	"benefits": 
}
}
And is this should be job advertisement data format?
